project:
  type: website
  output-dir: docs

website:
  title: "Gonzalo Torres | Inequality research"
  navbar:
    left:
      - href: index.qmd
        text: EN
      - href: index-es.qmd
        text: ES
      - href: research.qmd
        text: Research
      - href: teaching-data.qmd
        text: Teaching & Data Work
      - href: beyond-research.qmd
        text: Beyond Research
      - about.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

