project:
  type: website
  output-dir: docs

website:
  title: "Gonzalo Torres | Inequality research"
  navbar:
    left:
      - href: index.qmd
        text: EN
      - href: index-es.qmd
        text: ES
      - about.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

